name: girando
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+5

#flutter v- 3.3.4
environment:
  sdk: ">=2.17.5 <3.0.0"
  
dependencies:
  animate_do: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: ^2.0.0
  line_icons: ^2.0.1
  url_launcher: ^6.0.17
  clipboard: ^0.1.3
  animated_splash_screen: ^1.1.0
  cached_network_image: ^3.2.0
  badges: ^2.0.2
  lottie: ^1.2.2
  intl: ^0.17.0
  onesignal_flutter: ^3.2.8
  upgrader: ^4.6.0
  package_info_plus: ^1.4.3+1
  
dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
